### ISSUE TITLE
print the schema graphql

### ISSUE THREAD

**Issue by francescoagati** [tjwlucas/haxe-graphql-server-php#1]
hi,
there is a mode for printing or have the graphql schema generated from graphqlphp

**Comment by tjwlucas** [comment]
You mean in GraphQL schema language, such as this?
```gql
schema {
  query: Base
  mutation: BaseMutation
}

type Base {
  """Returns random"""
  random(n: Int = 10): [Float!]
}

type BaseMutation {
  mutate: Boolean!
}
```
There is now, it does still require the underlying `webonyx/graphql-php` library, since that is what everything is built around. Does that help?

**Comment by francescoagati** [comment]
yes really thanks
