### ISSUE TITLE
Solving N+1 Problem integration

### ISSUE THREAD

**Issue by francescoagati** [tjwlucas/haxe-graphql-server-php#4]
hi,
is possible use also this feature of graphql-php this can be useful in many cases.

https://webonyx.github.io/graphql-php/data-fetching/#solving-n1-problem

**Comment by tjwlucas** [comment]
I had considered that outside the scope of what I was trying to do, but now you mention it... I have a few ideas of how I might implement it, when I get a chance, so watch this space!

**Comment by francescoagati** [comment]
thanks

**Comment by francescoagati** [comment]
but maybe i can use the context for preloading the data i need

**Comment by tjwlucas** [comment]
@francescoagati  Context might have been able to help. But I've now had a chance to have a look.
https://github.com/tjwlucas/haxe-graphql-server-php#deferred-resolvers-n1-problem

Does this satisfy your use case?

**Comment by francescoagati** [comment]
yes really useful thanks
