### ISSUE TITLE
make all code async

### ISSUE THREAD

**Issue by francescoagati** [tjwlucas/haxe-graphql-server-php#8]
hi,
i have see the intetration with javascript graphql. but javascript and php have a different concurrency model. i think that all the method of the objects graphql should return a promise because in javascript for access any external source you must use a callback and a promise. and also in php there are some example of concurrency mode live in javascript (see ReactPhp for example). you should try to see tink.core where there is a example of Future class that cang generate futures sync and async

**Comment by tjwlucas** [comment]
I agree about the different models, and JavaScript needing better async support. I'm trying to tread carefully to minimise *too* much target specific stuff, but at the very least mean to allow promises to be returned by resolvers (In fact, already intended this to be the case, I'm not at my computer to check, but if not, I consider that a bug). The aim is to implement async functionality in a way that can work between js and reactphp targets (this is also on the roadmap).

**Comment by francescoagati** [comment]
yes you could try to use Future from tink-core that work good in all targets.

for example
```
class Query implements GraphQLObject {
    public function new(){}    
    public function echo(message:String) : Future<String> {
        return Future.sync(message)
    }
    public function getObject() : Future<OtherObject> {
        return Future.async(handle -> {
                // some async code 
              handle(new OtherObject());

       });
    }
}

```

**Comment by tjwlucas** [comment]
I also agree about unifying the interface a bit between the two. As a temporary measure, until getting to that properly, b347f4f78d52389474f72008944f25598b830834 will allow returning a javascript promise, in the same way as a `Future` from the php library, so that code that returns Promises can at least be used, such as the (trivial) example in the associated test case:
```haxe
    #if php
    public function manualDeferredObject() : graphql.externs.Deferred<String> {
        return new graphql.externs.Deferred(() -> "Some string");
    }
    #elseif js
    public function manualDeferredObject() : js.lib.Promise<String> {
        return new js.lib.Promise((resolve, reject) -> resolve("Some string"));
    }
    #end
```

In both these cases, the GraphQL server will resolve it as a `String!` type returning `"Some string"`.

**Comment by francescoagati** [comment]
thanks it really work good
